apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: artharakiri/flask_oauth
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: google-id-secret
          #     env:
          #       - name: GOOGLE_CLIENT_ID
          #   valueFrom:
          #     secretKeyRef:
          #       name: google-id-secret
          #       key: GOOGLE_CLIENT_ID
          # - name: GOOGLE_CLIENT_SECRET
          #   valueFrom:
          #     secretKeyRef:
          #       name: google-id-secret
          #       key: GOOGLE_CLIENT_SECRET
